### ISSUE TITLE
Cleancode - 클린코드 추가 수정에 대하여

### ISSUE THREAD

**Issue by NewCenturyDev** [HyperTech99/OSS-MineSweeper#19]
이슈 제목과 내용은 추후 월요일날 issue의 세부 양식이 정해지는 대로 수정할 예정입니다.

main함수가 너무 방대해져서, main함수를 분할할 필요성이 있을 것 같습니다. (완료) 3eb4a40

또한, true와 false값을 기존에는 int형 상수로 정의하였으나,
visual studio 환경에서 C 언어 문법 및 표준 라이브러리만 사용하면서
bool 함수와 true, false 함수를 사용하는 방법을 찾아내어 개선하였습니다.
stdbool 헤더를 추가하면 됩니다. 따라서 불필요한 TRUE, FALSE 전역 변수 역시 감축합니다. (완료) 3eb4a40

그리고 아래 두 가지 사항을 점검할 필요가 있을 것 같습니다.

1. 미처 수정하지 못한 하드코딩된 부분(0,1,2,3 등 값이 적힌 부분)에 대한 파악
예시: PrintMineField(**0**, ...)
단, 1. 의 경우 명령어 분기처리 부분의 case문 옆에 적힌 하드코딩 상수에 대해서는 불가피하게 사용하되, 주석으로 해당 하드코딩 상수(== 명령어)에 대한 설명을 취하는 방식을 택해야 할 것 같습니다. (C언어 switch문법 특성상 하드코딩 상수 사용이 불가피합니다.) (완료) 021f11f

2. 조건문의 조건수식이 복잡한 연산으로 구성된 부분에 대한 파악 (완료) #29
예시: else if(**initSet.num >= initSet.width * initSet.height**)
꼭 필요한 부분과 내용만 있는 것을 확인했습니다.

**Comment by gusdn3477** [comment]
월요일에 뵙죠

**Comment by jspark9708** [comment]
전부 숙지했습니다.
완료 후 Close 하도록 해요.

**Comment by gusdn3477** [comment]
저 또한 숙지했습니다.

**Comment by NewCenturyDev** [comment]
모든 내용이 전부 반영되었으므로 이슈 닫겠습니다.
