### ISSUE TITLE
Revolution# - 분할컴파일

### ISSUE THREAD

**Issue by wwwoong** [HyperTech99/OSS-MineSweeper#21]
**기존에 어떠한 부분이 불편하셨나요?**
기존의 코드는 main.c 파일 하나에 모든 코드가 담겨있어서 코드를 기능 별로 보기 어려웠다.

**어떠한 기능을 추가하고 싶은지 설명해주세요**
지금 하나로 작성된 코드를 각 기능에 맞게 코드를 분할하여 코드를 분할 컴파일 가능하게 하겠다..

**Comment by NewCenturyDev** [comment]
분할 컴파일을 해야할 정도로 많은 부분을 클린코드화 및 예외처리 로직 개선, 추가하면서 양이 늘어난 것이 사실입니다..

허나 현재 남은 개발일정상 만약에 그렇게 하게 되면 몇가지 기능 추가를 포기하거나 다른 부분에서 타협이 필요할 것 같습니다. 다른 분들 의견은 어떠신가요?

**Comment by jspark9708** [comment]
기존의 코드는 양이 그렇게 많지 않아 분할하지 않기로 했었지만,
여러가지 수정을 거치면서 코드의 분량이 늘어났으니 분할 찬성합니다.

**Comment by gusdn3477** [comment]
원본 코드에 비해 코드의 양이 너무 늘어나 분할 컴파일이 필요한 순간이 된 것 같습니다.
분할 컴파일 찬성합니다.

**Comment by NewCenturyDev** [comment]
의견을 종합했을 때 분할 컴파일 작업을 하는 게 맞을 듯 합니다.

Project에도 분할컴파일 Note 올라왔으니 이슈 닫겠습니다.
