### ISSUE TITLE
Revolution# - 메인 화면 구성 변경

### ISSUE THREAD

**Issue by jspark9708** [HyperTech99/OSS-MineSweeper#22]
**기존의 불편한 점**
기존의 프로그램은 다른 일반적인 게임들과 비교해보았을 때,
메인화면이나 게임 시작화면을 거치지 않고 바로 게임이 시작되었으며

이는 도움말 기능이나 별도의 창을 구현하기로한 지금
변경해여야 할 부분이 되었다.

**추가하고 싶은 기능**
메인 타이틀을 추가한다.
메인 타이틀은 '게임시작', '도움말', '게임종료'.
이 세가지의 버튼을 고를수 있으며,
'게임시작' 선택 후 EASY, MEDIUM, HARD, EXPERT, CUSTOM으로
게임의 모드를 선택할 수 있도록 한다.

이 이슈는 windows.h 의 사용을 하지 않기로 결정할 경우. 적용하지 않도록 합니다.

**Comment by NewCenturyDev** [comment]
좋은 아이디어인 것 같습니다.. 찬성합니다!

**Comment by gusdn3477** [comment]
찬성합니다

**Comment by wwwoong** [comment]
찬성합니다.

**Comment by NewCenturyDev** [comment]
그럼 화면구성은 제성님 방안대로 하는걸로 결정된 것 같으니 이슈 닫겠습니다.
