### ISSUE TITLE
Bugfix# - stdbool.h 헤더 파일의 사용

### ISSUE THREAD

**Issue by jspark9708** [HyperTech99/OSS-MineSweeper#24]
**오류 메시지**
fatal error C1083: 포함 파일을 열 수 없습니다. 'stdbool.h': No such file or directory

**오류 발생 상황**
VS 2010 버전에서 작동시 생기는 오류입니다.

**원래 의도한 상황**
VS 2017에서는 정상 작동합니다

**해결 방안 제안**
구동 환경에 대한 범위를 바꾸거나, 해당 헤더의 사용을 재고해봐야할 것 같습니다.

**Comment by wwwoong** [comment]
저는 그래도 stdbool 을 사용하는 편이 좀 더 낫지 않을까 생각됩니다.

**Comment by gusdn3477** [comment]
저도 일단 지웅님 의견에 한 표 던지겠습니다. 버그를 미리 발견해 주셔서 감사합니다.

**Comment by gusdn3477** [comment]
저도 현재는 지웅님과 비슷한 생각을 하고 있습니다. 그러나 추후에 이러한 버그가 또 나타날 수 있는 가능성이 있기에 약간은 조심스럽군요.

**Comment by NewCenturyDev** [comment]
HyperTech99 19 hours ago Author Owner

VS2010 자체가 너무 낡아서 1999년 C 표준안조차도 제대로 지원하지 못한다고 합니다.

stdbool.h은 1999년부터 표준입니다.

물론 우리 팀에서 VS2010을 기준환경으로 삼자고 합의하기는 했지만, 1999년 문법까지 배제한다면 너무 지나친 거 같습니다.

1980년대 표준에 맞춰 C 프로그램을 작성하는 것은 너무 구식이고 비효율적이라고 생각합니다.

개선하기보다는 존치하되, VS2010을 위해서 stdbool.h를 동봉하는 방안이 더 나을 거 같습니다.

**Comment by jspark9708** [comment]
알겠습니다. 저도 동의합니다.
그럼  stdbool.h 헤더 파일의 사용은 계속하는 것으로 하겠습니다.
