### ISSUE TITLE
Bugfix# - 함수 TitleScreen, OptionScreen에서의 경고

### ISSUE THREAD

**Issue by jspark9708** [HyperTech99/OSS-MineSweeper#28]
**오류 메시지**
bugfix5 - 치트키가 작동 안 하는 오류 수정 기점 코드 기준
warning C4715: 'TitleScreen': 모든 제어 경로에서 값을 반환하지는 않습니다.
warning C4715: 'OptionScreen': 모든 제어 경로에서 값을 반환하지는 않습니다.

**오류 발생 상황**
case문의 default에서 값을 반환하지 않아 생기는 문제인듯 합니다.

**원래 의도한 상황**
do while 문에서 한정된 값 만을 입력 받도록 제한하였기에 switch문에서도 default가 작동 될 일이 없다고 생각하여.
이 한정된 값 만으로 switch문으로 타이틀 화면, 옵션 화면을 제작한 상태입니다.

**해결 방안 제안**
default 값에 더미 데이터를 넣는 것, 아니면 특정값을 return해서 경고문을 띄우도록 해야할 것 같습니다.

**Comment by NewCenturyDev** [comment]
#29 에서 같이 반영했습니다. 버그픽스 완료되었으므로 이슈 닫겠습니다.
